### ISSUE TITLE
Undefined method 'final' for OpenSSL::Digest

### ISSUE THREAD

**Issue by treagod** [grip-framework/grip#18]
**Describe the bug**
When trying to run a Grip application, it can't be compiled because the method `final` is not defined for `OpenSSL::Digest`.

**To Reproduce**
1. Start a new crystal project with `crystal init app <app_name>`
2. Add Grip dependency to `shards.yml`, exactly like in the README
3. Copy & Paste the Grip example from the readme to your code

**Expected behavior**
Have a running Grip server running

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Crystal 0.34.0

**Comment by grkek** [comment]
Try updating your Crystal version to 0.35.1
