### ISSUE TITLE
Grip::Pipes::Log show/print only HTTP status 200 requests

### ISSUE THREAD

**Issue by UrbanZan** [grip-framework/grip#19]
Hi,

first of all I would like to thank you for awesome work on the Grip project.

I followed the example https://github.com/grip-framework/grip/issues/17 and figured out that Grip::Pipes::Log show/print only HTTP status 200 requests. Is there an option to print unsuccessful requests through pipeline logger?

**Comment by grkek** [comment]
Hey there, thank you for this detail which I missed out, I removed the pipe from the source code and reverted to the central handler logging, it should be working by now just use the master branch in your shards.

I will release the updated version soon.

**Comment by UrbanZan** [comment]
@grkek you rock!

`2020-09-23 08:20:05 UTC 200 GET / 70.41µs
2020-09-23 08:20:08 UTC 404 GET /Test 35.84µs`

Is there any option to keep response time in log?

**Comment by grkek** [comment]
> @grkek you rock!
> 
> ```
> 2020-09-23 08:20:05 UTC 200 GET / 70.41µs
> 2020-09-23 08:20:08 UTC 404 GET /Test 35.84µs
> ```
> 
> Is there any option to keep response time in log?

Hm I don't think I understand what you mean here... @UrbanZan

**Comment by UrbanZan** [comment]
my bad, sorry...

I thought, if you will change or restructure the logic of logging, then don't forget to response time

**Comment by grkek** [comment]
> my bad, sorry...
> 
> I thought, if you will change or restructure the logic of current logging, then don't forget to response time

the microseconds in the log output are the response time indicators
