### ISSUE TITLE
Rendering HTML does not have a default encoding

### ISSUE THREAD

**Issue by vinyll** [grip-framework/grip#21]
The following code

```crystal
class Index < Grip::Controllers::Http
  def get(context : HTTP::Server::Context)
    context
      .html("<h1>Hello world 😄</h1>")
      .halt
  end
```

Should render `<h1>Hello world 😄</h1>`

Current rendering: `<h1>Hello world ð</h1>`

---

In order to do so, the `.html()` method could set the default encoding to `utf-8`.

In the meantime, skipping the shortcut does the job:

```crystal
class Index < Grip::Controllers::Http
  def get(context : HTTP::Server::Context)
    context
      .put_resp_header("Content-Type", "text/html; charset=utf-8")
      .send_resp("<h1>Hello world 😄</h1>")
      .halt
  end
```

**Comment by vinyll** [comment]
While I'm preparing a PR, I'm wondering it UTF-8 should not be the default for other content types too 🤔 

Also, I can't find test to adjust. Are there any somewhere?

**Comment by grkek** [comment]
Hello,

You can send a PR for the `html/1` method, something like this maybe?

```ruby
def html(content, header = "text/html; charset=utf-8")
  @response.headers.merge!({"Content-Type" => header})
  @response.print(content)
  self
end
```

So the `html/1` method will still be available as `html/2` for developers while giving you an optional argument and keeping the codebase intact.

**Comment by grkek** [comment]
@vinyll Can you provide same for other functions returning responses as well?

for `text/1`, `json/1` and `binary/1`.

The `binary/1` should look something like this:

```ruby
def binary(content, header = "application/octet-stream")
  @response.headers.merge!({"Content-Type" => header})
  @response.print(content)
end
```

**Comment by vinyll** [comment]
Hey, thanks for your support with the PR suggestion.
I know it would be faster to fix it yourself, and at the same time it's interesting for me to get a little task like this one.

I [just released a PR](https://github.com/grip-framework/grip/pull/22) but it's not considering the `.binary()` method yet.
Having a look right away 👀

**Comment by vinyll** [comment]
I've [updated the PR](https://github.com/grip-framework/grip/pull/22) to consider the `binary()` method.

**Comment by vinyll** [comment]
> Hello,
> 
> You can send a PR for the `html/1` method, something like this maybe?
> 
> ```ruby
> def html(content, header = "text/html; charset=utf-8")
>   @response.headers.merge!({"Content-Type" => header})
>   @response.print(content)
>   self
> end
> ```
> 
> So the `html/1` method will still be available as `html/2` for developers while giving you an optional argument and keeping the codebase intact.

What do _html/1_ and _html/2_ mean?

**Comment by grkek** [comment]
It's an arity representation, the number after the / represents the argument count the function takes.

**Comment by grkek** [comment]
@vinyll I added you to the official Gitter chat of the framework, [click here](https://gitter.im/grip-framework/grip) to view the chat.
