### ISSUE TITLE
Built in static asset server

### ISSUE THREAD

**Issue by danreeves** [grip-framework/grip#28]
Are there any plans to include a static file server in grip? Similar to how Kemal automatically serves the `/public` directory or Phoenix serves the `priv/static/` directory.

**Comment by grkek** [comment]
I will add it soon enough.

**Comment by grkek** [comment]
@UrbanZan @danreeves Added the public file handler, refer to docs for more information about how to set it up.

**Comment by danreeves** [comment]
Wow that was fast 😄

**Comment by grkek** [comment]
> Wow that was fast 😄

I just cloned the Amber framework file handler since it is pretty good at it, found a bug in it as well and created a PR for the Amber team, so its a fair bargain

**Comment by UrbanZan** [comment]
Thnx @grkek. @danreeves he is very fast ;)
