### ISSUE TITLE
Custom error handling and compile error

### ISSUE THREAD

**Issue by UrbanZan** [grip-framework/grip#31]
Hi,

I'm checking the example on https://grip-framework.github.io/docs/error_handling/ and when I run the test app, I get the next error:

There was a problem expanding macro 'error'

Code in src/napake.cr:39:5

 39 | error 403, ForbiddenController
      ^
Called macro defined in lib/grip/src/grip/dsl/macros.cr:82:7

 82 | macro error(error_code, resource)

Which expanded to:

 > 1 | @exception_handler.handlers[{{error_code}}] = {{resource}}.new
                                     ^---------
Error: undefined macro variable 'error_code'

I also tested the code(custom error pages) with my old examples from version 1.1.1 and the results are practically the same.

br, uz

**Comment by grkek** [comment]
I don't even know how this slipped through, I added macro tests to make sure it works next time.

Thank you 👍
