### ISSUE TITLE
JSON error bug

### ISSUE THREAD

**Issue by RonanzinDev** [grip-framework/grip#40]
So I'm having a problem passing the context.fetch_body_params function to context.json()

I wrote the code just like in the documentation example:

```crystal
def get(context : Context) : Context
  params =
    context
      .fetch_body_params

  context
    .json(params)
end
```

And it's giving me this error:

![Error](https://user-images.githubusercontent.com/67972224/130308676-70ab3f3e-9cbe-4d90-b4c8-accf55b57b43.png)

I'm sorry if it's my own mistake

**Comment by grkek** [comment]
It seems like the default `to_json(json)` overload is not implemented for the `URI::Params` structure.

**Comment by grkek** [comment]
```crystal
class URI
  struct Params
    def to_json
      @raw_params.to_json
    end
  end
end
```

This is how you can patch it up for a bit for it to work.

**Comment by RonanzinDev** [comment]
> ```crystal
> class URI
>   struct Params
>     def to_json
>       @raw_params.to_json
>     end
>   end
> end
> ```
> 
> This is how you can patch it up for a bit for it to work.

Maybe I understand, but where do I put this code? in the current project? (I'm a little noob yet)

**Comment by grkek** [comment]
> > ```crystal
> > class URI
> >   struct Params
> >     def to_json
> >       @raw_params.to_json
> >     end
> >   end
> > end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is how you can patch it up for a bit for it to work.
> 
> Maybe I understand, but where do I put this code? in the current project? (I'm a little noob yet)

Make a new file and name it `ext.cr` and put the code mentioned above into that file, require it after requiring `grip`.

**Comment by RonanzinDev** [comment]
thanks, it's working
