### ISSUE TITLE
Better json format

### ISSUE THREAD

**Issue by RonanzinDev** [grip-framework/grip#42]
Is there a better way to get a better json format, in grip? without these "/"

Here is my code :
![image](https://user-images.githubusercontent.com/67972224/131391963-55ae4ca6-9465-44e6-b9f1-7ad851cf5942.png)

and this is the response:
![image](https://user-images.githubusercontent.com/67972224/131392066-e23127b3-917d-45fd-8e94-6585d3361fca.png)

**Comment by grkek** [comment]
You put the user into a string, try using the user variable directly like this:

```crystal
context.json({"user": @user})
```
