### ISSUE TITLE
Feature request: File upload/download

### ISSUE THREAD

**Issue by cyangle** [grip-framework/grip#50]
**Is your feature request related to a problem? Please describe.**
Helper methods to handle file upload/download requests
Helper methods or documentation to handle streaming video/audio

Currently there's no documentation for how to upload/download files

**Describe the solution you'd like**
Have something similar to Kemal's `send_file` helper method in Controller class and documentation of example usages.

**Describe alternatives you've considered**

**Additional context**
It needs to handle uploading/downloading files and possibly even streaming for a video/audio website.

**Comment by grkek** [comment]
You do have [fetch_file_params](https://grip-framework.github.io/docs/context/#fetch_file_params) which gives you the file from multipart and you could create a handler to handle uploaded file paths and turn them downloadable.

**Comment by cyangle** [comment]
OK, then I think it's missing file donwload helper similar to kemal's [send_file](https://kemalcr.com/cookbook/file_download/).

There's [serve_file](https://github.com/grip-framework/grip/blob/e7c7ad670c4af5974fd719afe5db9eeff9ab02dd/src/grip/handlers/static.cr#L107) method in the static file handler but it's private and you can not access it from the Controller or the Context.

**Comment by grkek** [comment]
You could add it to the `context` component:

```crystal
def send_file(path)
end

def get(context : Context) : Context
  context.send_file("/path/to/your_file")
end
```

**Comment by cyangle** [comment]
I'll work on it when I have time.
