### ISSUE TITLE
Index syntax

### ISSUE THREAD

**Issue by notramo** [grip-framework/grip#53]
Why does Grip have so ugly method names like `context.get_resp_headers("Content-Type")`?
Idiomatic Crystal code should use the indexing syntax: `context.response.headers["Content-Type"]`

**Comment by grkek** [comment]
It is inspired by Phoenix, I don't really see anything "ugly" with method-naming such as that, no need to be rude!

**Comment by notramo** [comment]
Sorry, I didn't meant to be rude. Unfortunately, in Crystal community, non-idiomatic naming occurs in mostly the same projects that have bad code (probably because if the developer don't even know the Crystal naming conventions, then they don't know Crystal either). But I took a look at the code, and this project is quite well designed. It's just the Context methods that are unusual.

One problem I see is that as a newcomer, it's hard to see from the method names if it will raise or will return null.
For example, using idiomatic Crystal, it would be clear:
```crystal
context.request.headers["Referer"]? # this will return Nil if key doesn't exists
context.request.headers["Referer"] # this will raise if key doesn't exist
context.get_req_header("Referer") # I have to open the source of this framework to see what it does actually
```

**Comment by notramo** [comment]
After looking at the code, I noticed that Context is inherited from the Context in the standard library, so those methods are available as well. I rather use those as those might be familiar to developers coming from other Crystal microframeworks (e.g. Kemal). But those who come from Phoenix, might prefer these.
I will open a documentation PR to clarify this if you agree.
