### ISSUE TITLE
Do you accept contributions?

### ISSUE THREAD

**Issue by notramo** [grip-framework/grip#54]
@grkek I took a look into the source code, and it seems it is using older approaches, or solutions that were necessary with an older version of the standard library.
I want to contribute some improvements, but I only open PR if I know that it will get attention.

For example, `Grip::Parsers::ParameterBox::AllParamsType` is unnecessary as it's the same as the `JSON::Any::Type` in the latest version of the standard library.

Also, the standard library includes a `HTTP::Request#query_params` in the latest version.

There are some places in the documentation that could be improved also.

**Comment by grkek** [comment]
I pay attention to PR's ASAP, make a PR for the above-mentioned problems and I would be more than happy to take a look at them.
