### ISSUE TITLE
Handle arbitrary exceptions

### ISSUE THREAD

**Issue by notramo** [grip-framework/grip#56]
@grkek, I want to catch `JSON::SerializationError` without specifying `begin … rescue … end` block everywhere.
I read the source, and it seems it's not possible currently.
I am interested in implementing this. I have two ideas. If you agree, I can implement this.

# Approach 1
What do you think about changing the `@handlers` keys to be the type of `Exception` instead of status code?
Currently, custom exceptions have a `@status` code, and this is what is matched in the handlers.
I would create a base class `Grip::Exception::StatusException < Exception`, then inherit `404Error`, `500Error`, etc.
This is how it would be used:
```crystal
error 404Error, My404Page
error 500Error, My500Page
error JSON::SerializationError, JsonErrorPage
```

# Approach 2
Another approach could be to rename `@handlers` to `@status_handlers`, and create an `@exception_handlers` too.
Then the matching would be done on exception type. If it is a `Grip::Exceptions::Base`, then the current status code matching behavior would activate. This could be done by setting up a handler by default for `Grip::Exceptions::Base`, which would decide what page is rendered by matching `@status_handlers` using the currently implemented method.
I think this approach could be done without breaking existing code, as the `error` macro could decide which handler is set up (status or exception).
```crystal
error 404, My404Page # This is an Int32, then set up status code handler
error DivisionByZero, MyCalculatorErrorPage # This is an Exception, then set up exception handler
```

**Comment by grkek** [comment]
Actually a great idea, I will take a look into it once I will have time.

**Comment by notramo** [comment]
@grkek I can try to implement this, I just wait for your opinion on what approach should be followed. I would personally go with the second.

**Comment by acoolstraw** [comment]
What does `My404Page` represent here?

**Comment by notramo** [comment]
`class My404Page < Grip::Controllers::Exception`
