### ISSUE TITLE
Wrong behavoir of serve_static on Windows

### ISSUE THREAD

**Issue by 18183883296** [grip-framework/grip#59]
**On Windows**, when serve_static is set true, behaviors to request for local resources will lead to a series of errors, including 304 resp status to a request for static files, none response for requests to obtain data from database etc.
https://github.com/grip-framework/grip/blob/be4ac9fa204b3153fd69f49200712002154881ad/src/grip/handlers/static.cr#L29
`File.expand_path("/whois", "/") => C:\whois`
This may be part of the cause of the problem.

**Comment by 18183883296** [comment]
A quick fix https://github.com/grip-framework/grip/pull/58/commits/6af00fa3af53a58b8f55400d07a9ec914498975d

**Comment by grkek** [comment]
Thank you for this fix!
