### ISSUE TITLE
[Feature] Set routing for serving static files

### ISSUE THREAD

**Issue by yanecc** [grip-framework/grip#60]
I couldn't find a solution to serve static files in specified path in Crystal public api. It's a nice feature worth considering. Or anything already works now?

**Comment by grkek** [comment]
Could you explain the issue with more details?

**Comment by 18183883296** [comment]
Now to set routing for static files
``` Crystal
class DemoController < Grip::Controllers::Http
  def getHtml(context : Context) : Context
    context
      .send_file("./public/index.html")
  end
end

class Application < Grip::Application
  def initialize(@port : Int32)
    super(environment: "development", serve_static: true)

    scope "/" do
      get "/html", DemoController, as: :getHtml # This works well.

      scope "/foo" do
      get "/html", DemoController, as: :getHtml
      # Request to host/foo/html => ok
      # Request to other static files => 404 Not Found
      # In the url http://localhost/foo/static/js/main.2ee217bf.js, /foo is not expected.
      end
    end
  end
  ...
end
```
I prefer the way in gofiber
![QQ截图20230524221021](https://github.com/grip-framework/grip/assets/89304297/bbdcf078-72b3-4724-bdfb-acbbada390e3)

**Comment by grkek** [comment]
> Now to set routing for static files
> 
> ```crystal
> class DemoController < Grip::Controllers::Http
>   def getHtml(context : Context) : Context
>     context
>       .send_file("./public/index.html")
>   end
> end
> 
> class Application < Grip::Application
>   def initialize(@port : Int32)
>     super(environment: "development", serve_static: true)
> 
>     scope "/" do
>       get "/html", DemoController, as: :getHtml # This works well.
> 
>       scope "/foo" do
>       get "/html", DemoController, as: :getHtml
>       # Request to host/foo/html => ok
>       # Request to other static files => 404 Not Found
>       # In the url http://localhost/foo/static/js/main.2ee217bf.js, /foo is not expected.
>       end
>     end
>   end
>   ...
> end
> ```
> 
> I prefer the way in gofiber ![QQ截图20230524221021](https://user-images.githubusercontent.com/89304297/240631865-bbdcf078-72b3-4724-bdfb-acbbada390e3.png)

is [this](https://grip-framework.github.io/docs/application/#public_dir) what you are looking for?

**Comment by 18183883296** [comment]
> is [this](https://grip-framework.github.io/docs/static_file_handling/) what you are looking for?

I have set the static file directory and assigned serve_static true.
It can only handle request to root path, right?

**Comment by grkek** [comment]
> > is [this](https://grip-framework.github.io/docs/static_file_handling/) what you are looking for?
> 
> I have set the static file directory and assigned serve_static true. It can only handle request to root path, right?

Depends on how you structure your directories, for example:

```
public/
  images/
    cat.jpeg
  pages/
    cat.html

  index.html
```

You will be able to access `cat.jpeg` by `/images/cat.jpeg` and `cat.html` by `/pages/cat.html`.

**Comment by 18183883296** [comment]
I mean the prefix part of the path **unrelated to the file structure**.
I'm seeking for a portable solution.

For example, to access the same files
``` Go
app.Static("/foo", "./public") => GET http://localhost/foo/index.html
app.Static("/foo/bar", "./public") => GET http://localhost/foo/bar/index.html
app.Static("/foo/bar/baz", "./public") => GET http://localhost/foo/bar/baz/index.html
```

**Comment by grkek** [comment]
> I mean the prefix part of the path **unrelated to the file structure**. I'm seeking for a portable solution.
> 
> For example, to access the same files
> 
> ```go
> app.Static("/foo", "./public") => GET http://localhost/foo/index.html
> app.Static("/foo/bar", "./public") => GET http://localhost/foo/bar/index.html
> app.Static("/foo/bar/baz", "./public") => GET http://localhost/foo/bar/baz/index.html
> ```

It could be an interesting feature, I will leave this open.
