### ISSUE TITLE
Update minimum supported crystal version to 1.8.0

### ISSUE THREAD

**Issue by yanecc** [grip-framework/grip#65]
`Process.on_interrupt` was introduced into Crystal API since 1.8.0.

**Comment by grkek** [comment]
> `Process.on_interrupt` was introduced into Crystal API since 1.8.0.

I will implement a way to handle versions using macros to support every version of crystal since 0.36.0

**Comment by yanecc** [comment]
> > `Process.on_interrupt` was introduced into Crystal API since 1.8.0.
> 
> I will implement a way to handle versions using macros to support every version of crystal since 0.36.0

The method `Process.on_interrupt` became deprecated since 1.12.0, please consider using `Process.on_terminate` for later version as well.

**Comment by grkek** [comment]
#67 should be a fix for this issue
