### ISSUE TITLE
Testing a POST route that expects a file

### ISSUE THREAD

**Issue by messiias** [grip-framework/grip#68]
Hello everyone! Can someone please help me, because i don't know how to write the tests of a POST route that expects a file from a multipart request.

I tried to follow the [Crystal docs](https://crystal-lang.org/api/1.12.2/MIME/Multipart/Builder.html) that shows how to build a multipart into a IO since the spectator "post" macro expects the body to be a String, but it failed and i don't know how make it work.

**Comment by grkek** [comment]
Can you provide the example you used? @messiias

**Comment by messiias** [comment]
I figured out the problem, i didn't know how multipart form-data requests work, but at the end the problem was the headers, so basically i defined the Content-Type header specifying the boundary used on `MIME::Multipart::Builder` for the request and also the Content-Type and the Content-Disposition headers for the body, the result was this:

``` crystal
require "../spec_helper"

describe ExampleController do
  app = Application.new("test")
  io = IO::Memory.new
  multipart = MIME::Multipart::Builder.new(io)
  boundary = multipart.boundary
  scope = "/api/v1"

  request_path = "#{scope}/register/file"
  request_headers = HTTP::Headers { "Content-Type" => "multipart/form-data; boundary=#{boundary}" }
  multipart_headers = HTTP::Headers {
    "Content-Disposition" => "form-data; name=file; filename=\"test_file.csv\"",
    "Content-Type" => "text/csv"
  }

  context "when a request is sent with a file to log the work hours" do
    it "returns 200" do
      file = File.read("./spec/fixtures/test_file.csv")
      multipart.body_part(multipart_headers, file)
      multipart.finish

      response = post app, request_path, request_headers, io.to_s
      response.status_code.should eq 200
    end
  end
end
```
