### ISSUE TITLE
RE_USE port disabled by default

### ISSUE THREAD

**Issue by waghanza** [grip-framework/grip#71]
Hi @grkek,

I can see that this option is false by default

https://github.com/grip-framework/grip/blob/aa7ffe4a4ae4cf59049971226c0eabdbb2b40d7a/src/grip/application.cr#L44

Any reason about that ?

Regards,

**Comment by grkek** [comment]
You can override it like this,

```crystal
class Application < Grip::Application
  def reuse_port : Bool
    true
  end
end
```
