### ISSUE TITLE
Is there a way to run this with reuse_port: true ?

### ISSUE THREAD

**Issue by CaDs** [grip-framework/grip#8]
Hello I'm working on [having grip ready for TechEmpowerBenchmarks](https://github.com/CaDs/FrameworkBenchmarks/tree/adds_crystal_grip/frameworks/Crystal/grip)

I want to use all the cores available, so I was wondering if there is an option for passing 
```crystal
reuse_port: true
```
when running the application.
[Example of what we do at Kemal](https://github.com/CaDs/FrameworkBenchmarks/blob/adds_crystal_grip/frameworks/Crystal/kemal/server-postgres.cr#L139)

Thanks!

**Comment by grkek** [comment]
Hi there,

I am very glad for your time and effort, I was too busy to add Grip to the TechEmpowers benchmark and you've gone and done it!

Here is an [example](https://github.com/the-benchmarker/web-frameworks/blob/master/crystal/grip/src/server.cr) where the server is using a reuse port flag.

Thank you!

**Comment by CaDs** [comment]
Perfect, I will update the code.
Thanks!

**Comment by CaDs** [comment]
@grkek congratulations, [according to the benchmarks](https://www.techempower.com/benchmarks/#section=test&runid=64be2110-3011-48ae-8416-30c0ac0609c1&hw=ph&test=json&l=zdk8an-3j) you have created one of the fastest crystal frameworks so far 🙌
